### ISSUE TITLE
API - Internal error (class PoolMatchesTransformer)

### ISSUE THREAD

**Issue by LogLauncher** [CPNV-ES/Joutes#1]
In the file `app\Http\Response\Transformers\PoolMatchesTransformer.php`, there is a problem with these two lines of code:
```php
'contender1Name'    => (string) $game->contender1->team->name,
'contender2Name'    => (string) $game->contender2->team->name,
```
Under certain circumstances we get the following error:
```json
{
    "message": "Trying to get property of non-object",
    "status_code": 500
}
```
This error happens when the `$game->contenderX->team` returns **null** and we try to access the `name` property of a **null** object.
In the URL `http://joutes.api/api/events/1/tournaments/1/pools/{id}` replace `{id}` with a pool id that wasn't been populated with the teams yet.

**Comment by QuentinNev** [comment]
It has been fixed.
In the **PoolMatchesTransformer.php** it tries to give the name of contenders from an object, even if the concerned pool haven't any team in it. Now it check this before setting the name, and if it's empty the contender will have "no team" as their name.

**Comment by LogLauncher** [comment]
In my opinion, if a team wants to call themselves `"no team"` they should be allowed to do so and it shouldn't have an impact on the application.
But with what you are returning that won't be possible. Because on our end, we'll check if the team is `"no team"` and display an error message or display a different name in the field. So if a team decides to call themselves `"no team"` it will not be displayed correctly.

If possible you should return `null` or in the worst case return an empty string `""`.
Here is my proposition on how to do it:
```php
 'contender1Name'    => (empty($game->contender1->team) ? null: $game->contender1->team->name),
 'contender2Name'    => (empty($game->contender2->team) ? null: $game->contender2->team->name),
```

If you could change it that would be great.
Thank you very much.

**Comment by QuentinNev** [comment]
You're right, it was stupid to not set it to null from the start, my bad.

**Comment by LogLauncher** [comment]
Thank you
