### ISSUE TITLE
Error 500 after privileged user session expiration

### ISSUE THREAD

**Issue by phurni** [CPNV-ES/Joutes#13]
When a session expires, especially when the user is an Administrator, a URL protected by Check* middleware will return a 500 instead of a 401. This is because the code ( CheckIsParticipantOrAdmin.php@19 ) doesn't take into account that Auth::user() may be null.
All the other middlewares that checks roles should be affected.

**Comment by QuentinRo** [comment]
Debuged in  000150f0a741afd0132083f43926cdccccae51e8
